<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/26
 * Time: 22:05
 */

namespace app\bis\controller;
use think\Controller;

class Base extends Controller
{
    public function _initialize()
    {
        $this->isLogin();

        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function isLogin(){
        if (!session('bisAccount','','bis')){
            $this->error('请登录','login/index');
        }
    }



}